spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coupon
    username: coupon
    password: coupon1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop       # 개발용. 운영이면 validate
    defer-datasource-initialization: true   # 테이블 생성(JPA) 후 data.sql 실행
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
    consumer:
      group-id: coupon-issue-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: "com.example.fcfm.coupon.*"