spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coupon
    username: coupon
    password: coupon1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop       # 개발용. 운영이면 validate
    defer-datasource-initialization: true   # 테이블 생성(JPA) 후 data.sql 실행
    properties:
      hibernate:
        format_sql: true
    show-sql: true